org: docker.pkg.github.com/rmb938/linuxkit-pkg-containerd
image: containerd
network: true
arches:
  - amd64
config:
  binds:
  - /dev:/dev
  - /etc/resolv.conf:/etc/resolv.conf:ro

  # SHARE NODE PATHS START
  - /run/node:/run:rshared,rbind # /run
  - /var/node/var:/var:rshared,rbind # /var

  - /var/node/etc/kubernetes:/etc/kubernetes:rshared,rbind # /etc/kubernetes
  - /var/node/etc/cni/net.d:/etc/cni/net.d:rshared,rbind # /etc/cni/net.d
  - /var/node/opt/cni/bin:/opt/cni/bin:rshared,rbind # /opt/cni/bin
  mounts:
  - type: bind
    source: /sys/fs/cgroup
    destination: /sys/fs/cgroup
    options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
  capabilities:
  - all
  rootfsPropagation: shared
  pid: host
  runtime:
    mkdir:
      - /run/node
      - /var/node/var
      - /var/node/etc/kubernetes
      - /var/node/etc/cni/net.d
      - /var/node/opt/cni/bin
